#!/bin/bash
# npm Publish Script for @zovo packages
# Generated by T12 - npm Publish Agent
# Date: 2026-03-03

set -e

PACKAGES_DIR="~/zovo-oss/zovo-types-webext/packages"

# Check for npm authentication
if ! npm whoami &>/dev/null; then
    echo "❌ Not logged into npm. Please run 'npm login' first."
    exit 1
fi

echo "✅ Logged into npm as: $(npm whoami)"

# Array of packages to publish
PACKAGES=(
    "type-helpers"
    "types-chrome-extension"
    "types-edge-extension"
    "types-firefox-extension"
    "types-safari-extension"
    "types-webext-common"
    "types-webext-full"
    "crx-compatibility-check"
)

for pkg in "${PACKAGES[@]}"; do
    echo "📦 Publishing @zovo/$pkg..."
    cd "$PACKAGES_DIR/$pkg"
    npm publish --access public
    echo "✅ Published @zovo/$pkg"
done

echo "🎉 All packages published successfully!"
